notifications:
  email: false

# if: tag IS present

os: linux
language: minimal
services:
  - docker
env:
  - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
  - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  - DOCKER_IMAGE=quay.io/pypa/manylinux2010_i686
  - DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
  - DOCKER_IMAGE=quay.io/pypa/manylinux2014_i686
install:
  - docker pull $DOCKER_IMAGE
script:
  - echo "Current working directory:" $PWD
  - docker run --rm -e MANYLINUX=yes -v `pwd`:/io/pysplash -w /io/pysplash $DOCKER_IMAGE ./build-wheels.sh
  - docker run --rm -e MANYLINUX=yes -v `pwd`:/io/pysplash -w /io/pysplash $DOCKER_IMAGE ./test-wheel.sh
  - ls wheelhouse/

jobs:
  include:
    - name: MacOS build
      os: osx
      language: minimal
      env:
        -
      install:
        - ln -f -s $(which python3) $(which python) # force re-link python --> python3
        - ln -f -s $(which pip3) $(which pip)       # force re-link    pip --> pip3
        - pip install delocate virtualenv
      script:
        - echo "Current working directory:" $PWD;
        - ./build-wheels.sh
        - ./test-wheel.sh
        - ls wheelhouse/
