notifications:
  email: false

if: tag IS blank

dist: bionic
language: python
python: "3.6"
services: docker

env:
  global:
    - TWINE_USERNAME=__token__
    - secure: "lXmUGtxkmTNamFlsrzMA5Wdsx8w68sSeMzq0Rc188mNkeWlpUd8yq2EUZAagMrRgOjfmku39c36mmupYAo/4YqkzAB8gxcyzlP6qZXpEmryfRiBYnExqAR4fbdHKrOWBZd1fStAsBPbom7/pTAzAYcjHA3GshYXZbcyYXh9zjOT5wrA5YryfNP8qajNx9flNhoEVcpLb2hjaAQtpIIDdUwt/fB95FJA1FvEbyL52tnqzfAGcvQv4B9w83pE7IEuzV1eQsSz69upj280oZrXl3TsW9sqY2TvTiPzYaRCenRhu9ISJO0QGgRxOwx4V73260Gta8UD/T61FbAkiMNN+6vmSKSQsfztfv5iV07aBWKV49AbES/LQ1Sy1zZr3d4hS4J0yOkAT4RZ7MYFMAUZn4f+ItPFmh7SEcdOl3rlg59qXvz+KFyBs3U09TBXmB48f4/Mq5bJjXWuV8SizadjrBpmfWDXgRmd8xlv/1D2uAlehhvAX8i0/lRV4xz9StRzOm9UKnzf1d1guGZIsL4gugjdVoyfTrw4dxOE7fygzW2m3YdfrYhNiY/H2oAlLMIrICi+XX4ATeyiOl8srH+0uAsY/x2JlF+AURamEOKruZ46wAQQ2EvSjdlCTySM9mvakc6SX90fSgpKyAMaoQzjSW1UxFa6yZrHseOTecEVI9Cg="
  jobs:
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
    - DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64

install:
  - pip install twine
  - docker pull $DOCKER_IMAGE
script:
  - echo "Current working directory:" $PWD
  - docker run --rm -e MANYLINUX=yes -v `pwd`:/io/pysplashsph -w /io/pysplashsph $DOCKER_IMAGE ./build-wheels.sh
  - docker run --rm -e MANYLINUX=yes -v `pwd`:/io/pysplashsph -w /io/pysplashsph $DOCKER_IMAGE ./test-wheel.sh
  - ls wheelhouse/
  - ./twine-upload.sh

jobs:
  include:
    - name: MacOS build
      os: osx
      language: minimal
      services:
        -
      env:
        -
      install:
        - ln -f -s $(which python3) $(which python) # force re-link python --> python3
        - ln -f -s $(which pip3) $(which pip)       # force re-link    pip --> pip3
        - pip install delocate virtualenv pytest twine
      script:
        - echo "Current working directory:" $PWD;
        - ./build-wheels.sh
        - ./test-wheel.sh
        - ls wheelhouse/
        - ./twine-upload.sh
